In [1]:
import numpy as np

In [3]:
X = 2 * np.random.rand(100, 1)
y = 4 + 3 * X + np.random.randn(100, 1)

In [7]:
X_b = np.c_[np.ones((100, 1)), X]

In [10]:
X_b[:3]

array([[1.        , 1.28783066],
       [1.        , 1.64433528],
       [1.        , 0.22001592]])

In [11]:
theta_best = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)

In [12]:
theta_best

array([[4.34436066],
       [2.63557021]])

In [13]:
X_b.T.dot(X_b)

array([[100.        , 100.87084339],
       [100.87084339, 134.44682669]])

In [14]:
np.linalg.inv(X_b.T.dot(X_b))

array([[ 0.04111831, -0.03084966],
       [-0.03084966,  0.03058333]])

In [19]:
np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)

array([[4.34436066],
       [2.63557021]])

In [17]:
y.shape

(100, 1)