In [19]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
np.set_printoptions(precision=4)

## `SparseCategoricalCrossentropy()`

In [24]:
y_true = np.array([1, 2])
y_pred = np.array([[0.05, 0.95, 0], [0.1, 0.8, 0.1]])
# Using 'auto'/'sum_over_batch_size' reduction type.
scce = keras.losses.SparseCategoricalCrossentropy()
scce(y_true, y_pred)


<tf.Tensor: shape=(), dtype=float32, numpy=1.1769392>

In [31]:
y_true = tf.constant([1, 2])
y_pred = tf.constant([[0.05, 0.95, 0], [0.1, 0.8, 0.1]])
# Using 'auto'/'sum_over_batch_size' reduction type.
scce = keras.losses.SparseCategoricalCrossentropy()
scce(y_true, y_pred)


<tf.Tensor: shape=(), dtype=float32, numpy=1.1769392>

In [23]:
# Calling with 'sample_weight'.
scce(y_true, y_pred, sample_weight=np.array([0.3, 0.7]))


<tf.Tensor: shape=(), dtype=float32, numpy=0.8135988>

In [25]:
# Using 'sum' reduction type.
scce = keras.losses.SparseCategoricalCrossentropy(
    reduction="sum")
scce(y_true, y_pred)


<tf.Tensor: shape=(), dtype=float32, numpy=2.3538785>

In [26]:
# Using 'none' reduction type.
scce = keras.losses.SparseCategoricalCrossentropy(
    reduction=None)
scce(y_true, y_pred)


<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.0513, 2.3026], dtype=float32)>

---

## `CategoricalCrossentropy()`

In [51]:
target = np.array([[1., 0., 0.], [0., 1., 0.], [0., 0., 1.]])
output = np.array([[1., 0., 0.], [.05, .89, .06], [.05, .01, .94]])
loss = scce = keras.losses.CategoricalCrossentropy(from_logits=True)
loss(target, output)

<tf.Tensor: shape=(), dtype=float32, numpy=0.5889537>

In [52]:
target = np.array([[1., 0., 0.], [0., 1., 0.], [0., 0., 1.]])
output = np.array([[1., 0., 0.], [.05, .89, .06], [.05, .01, .94]])
loss = scce = keras.losses.CategoricalCrossentropy()
loss(target, output)

<tf.Tensor: shape=(), dtype=float32, numpy=0.059469786>